### ISSUE TITLE
asset-example contract fails to compile

### ISSUE THREAD

**Issue by zabuxx** [AstarNetwork/chain-extension-contracts#15]
![image](https://github.com/AstarNetwork/chain-extension-contracts/assets/18469570/f4a36d0a-6557-42e5-8a2f-b91f8869bed9)

Similar to: https://github.com/AstarNetwork/ink-test-contracts/issues/5

Same fix can be used

**Comment by PierreOssun** [comment]
The Cargo.toml does not target this branch. Compilation works (tested)
